import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const distDir = path.resolve(rootDir, 'dist');
const distAssets = path.resolve(distDir, 'assets');
const rootAssets = path.resolve(rootDir, 'assets');
const distHtml = path.resolve(distDir, 'template.html');
const distIndex = path.resolve(distDir, 'index.html');
const rootIndex = path.resolve(rootDir, 'index.html');
const root404 = path.resolve(rootDir, '404.html');
const dist404 = path.resolve(distDir, '404.html');

// 1. Ensure dist/index.html exists for Capacitor / mobile build
if (fs.existsSync(distHtml)) {
  fs.copyFileSync(distHtml, distIndex);
  fs.copyFileSync(distHtml, dist404);
}

// 2. Read template.html or index.html from dist (clean HTML generated by Vite)
const sourceHtmlPath = fs.existsSync(distHtml) ? distHtml : distIndex;
if (!fs.existsSync(sourceHtmlPath)) {
  console.error('Error: Neither dist/template.html nor dist/index.html was found!');
  process.exit(1);
}

let htmlContent = fs.readFileSync(sourceHtmlPath, 'utf8');

// 3. Write clean root index.html and 404.html referencing ./assets/
fs.writeFileSync(rootIndex, htmlContent, 'utf8');
fs.writeFileSync(root404, htmlContent, 'utf8');
console.log('✓ Successfully wrote clean root index.html and 404.html');

// 4. Sync dist/assets/ to root assets/ so GitHub Pages serves them properly
if (fs.existsSync(distAssets)) {
  if (fs.existsSync(rootAssets)) {
    fs.rmSync(rootAssets, { recursive: true, force: true });
  }
  fs.cpSync(distAssets, rootAssets, { recursive: true });
  console.log('✓ Synced dist/assets to root assets/');
}

// 5. Sync public folder files to both root and dist
const publicDir = path.resolve(rootDir, 'public');
if (fs.existsSync(publicDir)) {
  const publicFiles = fs.readdirSync(publicDir);
  for (const file of publicFiles) {
    const src = path.join(publicDir, file);
    fs.copyFileSync(src, path.join(rootDir, file));
    fs.copyFileSync(src, path.join(distDir, file));
  }
  console.log('✓ Synced public files (version.json, chatbase.png, svg icons) to root and dist');
}

// 6. Ensure CNAME exists in root and dist
const cnameRoot = path.resolve(rootDir, 'CNAME');
const cnameDist = path.resolve(distDir, 'CNAME');
if (!fs.existsSync(cnameRoot)) {
  fs.writeFileSync(cnameRoot, 'chat.webguruji.online\n', 'utf8');
}
fs.copyFileSync(cnameRoot, cnameDist);
console.log('✓ Ensured CNAME (chat.webguruji.online) exists in root and dist');

// 7. Ensure .nojekyll exists in root and dist for GitHub Pages
const noJekyllRoot = path.resolve(rootDir, '.nojekyll');
const noJekyllDist = path.resolve(distDir, '.nojekyll');
fs.writeFileSync(noJekyllRoot, '', 'utf8');
fs.writeFileSync(noJekyllDist, '', 'utf8');
console.log('✓ Ensured .nojekyll exists in root and dist');
